theme = "yolo"

[editor]
auto-pairs = false
auto-format = false 
auto-completion = false
gutters = ["spacer"]
bufferline = "multiple"

[editor.lsp]
enable = false # seemingly I need to turn off all lsp's so the rust one stops being so annoying
display-messages = false
auto-signature-help = false
display-inlay-hints = false 
display-signature-help-docs = false
snippets = false

[editor.file-picker]
hidden = false

[editor.statusline]
right = ["position-percentage", "selections"]
mode.normal = ":/"
mode.insert = ">:)"
mode.select = ":0"

[editor.soft-wrap]
enable = true
