theme = "yolo"

[editor]
auto-pairs = false
auto-format = true
auto-completion = false


[editor.lsp]
display-messages = false
auto-signature-help = false
display-signature-help-docs = false

[editor.file-picker]
hidden = false

[editor.statusline]
right = ["position-percentage", "selections"]
