#!/usr/bin/env fish

set script_path (cd (status dirname); pwd -P)

#set background

if test -x (command -v feh)
    feh --bg-scale $script_path/down.jpg
end

leftwm-command "UnloadTheme"

pkill lemonbar
pkill compton
pkill picom
pkill lemonbar

echo "going down!"
