#!/usr/bin/env fish

# fish port of lemonbar theme's up

set script_path (cd (status dirname); pwd -P)

#down the last running theme
# originally [ -f ]. not sure if test -e is the same

if test -e "/tmp/leftwm-theme-down"
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
end
ln -s $script_path/down /tmp/leftwm-theme-down

#boot compton or picom if it exists

if test -x (command -v compton)
    compton &> /dev/null & 
else if test -x (command -v picom) 
    picom &> /dev/null &
end

#set the theme.ron config

leftwm-command "LoadTheme $script_path/theme.ron"

#set background

if type -q feh
    feh --bg-scale $script_path/background.jpg
end 

#boot lemonbar and pipe the status of left into it
# NOTE: will not use lemonbar. Just here to see if it affects other parts of leftwm. 

# open firefox
firefox

# open alacrity
# why isn't this working??
alacritty

# ^ how to get these on different workspaces?
leftwm-command "SendWorkspaceToTag 1 hello"
leftwm-command "SendWindowToTag hello"