inherits = "mellow"

[palette]
bg = "#0d000d"
fg = "#c9c7cd"
bg_dark = "#131314"

black = "#27272a"
bright_black = "#353539"

red = "#f5a191"
bright_red = "#ffae9f"

#green = "#a6a5b5"
#bright_green = "#b2b1c1"

green = "#90b99f"
bright_green = "#9dc6ac"

yellow = "#e6b99d"
bright_yellow = "#f0c5a9"

blue = "#aca1cf"
bright_blue = "#b9aeda"

magenta = "#e29eca"
bright_magenta = "#ecaad6"

cyan = "#ea83a5"
bright_cyan = "#f591b2"

white = "#c1c0d4"
bright_white = "#cac9dd"

gray01 = "#1b1b1d"
gray02 = "#2a2a2d"
gray03 = "#3e3e43"
gray04 = "#57575f"
gray05 = "#757581"
gray06 = "#9998a8"
gray07 = "#c1c0d4"